version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - pauldub
  assignees:
  - pauldub
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.12.1
